openapi: 3.2.0
info:
  title: Deals External Agent API
  version: 1.0.0
  description: '## Index


    For partner integration use (25.01.00)


    ### Getting Started


    #### Getting a JWT Access Token


    `POST https://authentication.api.lwolf.com/v1/login`


    All APIs require an *Authorization* HTTP Header that contains a *Bearer {token}* as its value.'
servers:
- url: https://deals.api.lwolf.com
  description: Base URL declared by the provider in apis.yml (roadmap#122).
security:
- BearerToken: []
tags:
- name: External Agent
paths:
  /external-agents/{externalAgentId}:
    get:
      summary: Get an external agent
      description: Using the external agent guid in the request path, the method requests an external agent.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Retrieved external agent successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: getExternalAgentsByExternalAgentId
      x-operation-id-source: derived
    patch:
      summary: Update an external agent
      description: Updates an external agent based on their external agent guid.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successfully updated an external agent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '412':
          description: Optimistic concurrency check failed. The If-Match header is missing or it does not contain the version currently in the database.
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalAgent'
            example:
              id: string (UUID)
              typeCode: string
              companyName: string
              prefix: string
              firstName: string
              middleName: string
              lastName: string
              suffix: string
              endCode: string
              payBroker: boolean
              taxId: string
              taxExempt: boolean
              taxCharged: boolean
              use1099: boolean
              mlsId: string
              addresses:
              - typeCode: string
                line1: string
                line2: string
                city: string
                provinceCode: string
                postalCode: string
                countryCode: string
              phoneNumbers:
              - typeCode: string
                ext: string
                number: string
              emailAddresses:
              - typeCode: string
                address: string
      operationId: patchExternalAgentsByExternalAgentId
      x-operation-id-source: derived
    delete:
      summary: Delete an external agent
      description: Deletes an external agent using their external agent guid.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successfully deleted an external agent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: deleteExternalAgentsByExternalAgentId
      x-operation-id-source: derived
  /deals/{dealId}/external-agents:
    get:
      summary: Get all external agents
      description: Using the deal guid in the request path, the method requests the associated external agents.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: dealId
        in: in path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Retrieved external agents successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: Deal not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: getDealsByDealIdExternalAgents
      x-operation-id-source: derived
    post:
      summary: Create an external agent
      description: Creates an external agent with a deal guid.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: dealId
        in: in path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '201':
          description: Successfully created an external agent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '409':
          description: External agent already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalAgent'
            example:
              id: string (UUID)
              typeCode: string
              companyName: string
              prefix: string
              firstName: string
              middleName: string
              lastName: string
              suffix: string
              endCode: string
              payBroker: boolean
              taxId: string
              taxExempt: boolean
              taxCharged: boolean
              use1099: boolean
              mlsId: string
              addresses:
              - typeCode: string
                line1: string
                line2: string
                city: string
                provinceCode: string
                postalCode: string
                countryCode: string
              phoneNumbers:
              - typeCode: string
                ext: string
                number: string
              emailAddresses:
              - typeCode: string
                address: string
      operationId: postDealsByDealIdExternalAgents
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/phone-numbers:
    post:
      summary: Create external agent phone number
      description: Using the external agent id in the request path, the method creates the contact's phone number.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Created phone number successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneNumber'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Phone number already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneNumber'
            example:
              typeCode: string
              ext: string
              number: string
      operationId: postExternalAgentsByExternalAgentIdPhoneNumbers
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/email-addresses:
    post:
      summary: Create external agent email address
      description: Using the external agent id in the request path, the method creates the contact's email address.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Created email address successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailAddress'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Email address already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailAddress'
            example:
              typeCode: string
              address: string
      operationId: postExternalAgentsByExternalAgentIdEmailAddresses
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/addresses:
    post:
      summary: Create external agent address
      description: Using the external agent id in the request path, the method creates the contact's address.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Created address successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Email address already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
            example:
              typeCode: string
              line1: string
              line2: string
              city: string
              provinceCode: string
              postalCode: string
              countryCode: string
      operationId: postExternalAgentsByExternalAgentIdAddresses
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/email-addresses/{emailAddressTypeCode}:
    patch:
      summary: Update external agent email address
      description: Using the external agent id and email address type code in the request path, the method updates the email address fields specified in the request body.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      - name: emailAddressTypeCode
        in: in path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully updated the email address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent or email address not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Email address already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '412':
          description: Optimistic concurrency check failed. The If-Match header is missing or it does not contain the version currently in the database.
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailAddress'
            example:
              typeCode: string
              address: string
      operationId: patchExternalAgentsByExternalAgentIdEmailAddressesByEmailAddressTypeCode
      x-operation-id-source: derived
    delete:
      summary: Delete external agent email address
      description: Deletes the external agent's email address specified using the external agent id and email address type code path variables.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      - name: emailAddressTypeCode
        in: in path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully deleted the email address.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent or email address not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: deleteExternalAgentsByExternalAgentIdEmailAddressesByEmailAddressTypeCode
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/phone-numbers/{phoneNumberTypeCode}:
    patch:
      summary: Update external agent phone number
      description: Using the external agent id and phone number type code in the request path, the method updates the phone number.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      - name: phoneNumberTypeCode
        in: in path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully updated the phone number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent or phone number not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Phone number already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '412':
          description: Optimistic concurrency check failed. The If-Match header is missing or it does not contain the version currently in the database.
        '500':
          description: Unknown error. See response body for details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneNumber'
            example:
              typeCode: string
              ext: string
              number: string
      operationId: patchExternalAgentsByExternalAgentIdPhoneNumbersByPhoneNumberTypeCode
      x-operation-id-source: derived
    delete:
      summary: Delete external agent phone number
      description: Deletes the external agent's phone number specified using the external agent id and phone number type code path variables.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      - name: phoneNumberTypeCode
        in: in path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully deleted the phone number.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent or phone number not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: deleteExternalAgentsByExternalAgentIdPhoneNumbersByPhoneNumberTypeCode
      x-operation-id-source: derived
  /external-agents/{externalAgentId}/addresses/{addressTypeCode}:
    delete:
      summary: Delete external agent address
      description: Deletes the external agent address specified using the external agent id and address type code path variables.
      tags:
      - External Agent
      security:
      - BearerToken: []
      parameters:
      - name: externalAgentId
        in: in path
        required: true
        schema:
          type: string
      - name: addressTypeCode
        in: in path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully deleted the contact's address.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalAgent'
        '400':
          description: Invalid request. See response body for details.
        '401':
          description: Unauthorized request. See response body for details.
        '403':
          description: Permission denied. See response body for details.
        '404':
          description: External agent or address not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Unknown error. See response body for details.
      operationId: deleteExternalAgentsByExternalAgentIdAddressesByAddressTypeCode
      x-operation-id-source: derived
components:
  schemas:
    ApiError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            type: string
    ExternalAgent:
      type: object
    EmailAddress:
      type: object
    Address:
      type: object
    PhoneNumber:
      type: object
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JSON Web Token obtained from the Authentication API (`POST /v1/login`). Pass the token as `Authorization: Bearer <token>` in every request. Tokens expire after the number of seconds specified in the `expiresIn` field of the login response.'
